/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.osprojclone_3_newfx.CPUSchedulersSimulator;

public class FakeClass {
    public boolean someClassMethod() {
        return true;
    }
}
